---
- name: This playbook install packages
  hosts: all
  become: True
  tasks:
  - name: install httpd
    yum: 
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache

  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache
    ignore_errors: yes

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start_apache

  - name: copy web application
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
