---
- name: This playbook remove packages
  hosts: all
  become: True
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"
    ignore_errors: True
    
  - name: remove httpd
    yum: 
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

  - name: stop apache2 service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"
    ignore_errors: True

  - name: remove apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
