---
- name: This playbook install packages
  hosts: all
  become: True
  vars:
    port: 8008
  tasks:
  - name: install httpd
    yum: 
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start httpd

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  - name: copy web application
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  - name: Ensure the default Apache port is {{ port }}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen'
      insertafter: '^#Listen'
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart httpd

  - name: Ensure the default Apache port is {{ port }} on Ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen'
      insertafter: '# /etc/apache2/sites-enabled/000-default.conf'
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache2

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: restart httpd
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: restart apache2
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
